### ISSUE TITLE
kde wayland, working but isn't acutally the wallpaper

### ISSUE THREAD

**Issue by Redhawk18** [GhostNaN/mpvpaper#45] opened 2023-04-07 02:22 UTC
`mpvpaper -o  "no-audio" '*' XCDEMainMenuScreen1080p20Mbps2.mp4`

So I want to have a animated wallpaper, but maybe the layer isnt correct? The command works, but for example when I click the desktop button in the bottom right. It shows my background and the video background doesn't come back until i click on another app.

also if you could help me adding infinite looping to my video.

**Comment by GhostNaN** [comment] 2023-04-07 02:40
> The command works, but for example when I click the desktop button in the bottom right. It shows my background and the video background doesn't come back until i click on another app.

See here as to why: https://github.com/GhostNaN/mpvpaper/issues/13
But in short, it's not a supported feature by design.

> also if you could help me adding infinite looping to my video.

It's running mpv so just about anything you can do in mpv you can do with mpvpaper.
Just pass the relevant mpv arguments using ```--mpv-options  -o``` 
You want to use loop here: https://mpv.io/manual/master/#options-loop
So in your case you could use ```mpvpaper -o "--loop" "*" /path/to/media```

Besides that, I'm closing this issue.
KDE is not supported by mpvpaper unless KWin suddenly starts running on [wlroots](https://gitlab.freedesktop.org/wlroots/wlroots).
You could either ignore the issue or look for an alternative like this [kde plugin](https://github.com/catsout/wallpaper-engine-kde-plugin).

**Closed by GhostNaN** 2023-04-07 02:40 UTC
